MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 10.9                       # [osx and x86_64]

libboost_devel:
  - 1.88
python:
  - 3.9
  - 3.10
  - 3.11
  - 3.12
  - 3.13

pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
